config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.heroPage_view, name='heroPage'),
    path('layout', views.layout_view),
    path('home', views.home_view, name='home'),
    path('projetos', views.projetos_view, name='projetos'),
    path('contact', views.contact_view, name='contact'),
    path('licenciatura', views.licenciatura_view, name='licenciatura'),
    path('heroPage', views.heroPage_view, name='heroPage'),
    path('blog', views.blog_view, name='blog'),
    path('quizz', views.quizz_view, name='quizz'),
    path('login', views.login_view, name='login'),
    path('tfc', views.trabalhosFinaisCurso_view, name='tfc'),
    path('tempo', views.tempo_view, name='tempo'),
    path('tfcdetails/<int:tfc_id>', views.tfcdetails_view, name='tfcdetails'),
    path('logout', views.logout_view, name='logout'),
    path('trabalhosFinaisCurso', views.trabalhosFinaisCurso_view, name='trabalhosFinaisCurso'),
]

portfolio/models.py
from django.db import models


# Create your models here.
class Post(models.Model):
    titulo = models.CharField(max_length=200)
    descricao = models.TextField()
    link = models.URLField(blank=True)
    autor = models.CharField(max_length=100)
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo[:50]


class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length=200)
    pontuacao = models.TextField()

    def __str__(self):
        return self.nome[:50]


class Professor(models.Model):
    nome = models.CharField(max_length=20)
    linkLusofona = models.URLField
    linkLinkedin = models.URLField

    def __str__(self):
        return self.nome


class Projeto(models.Model):
    nome = models.CharField(max_length=20)
    descricao = models.CharField(max_length=255)
    imagem = models.ImageField

    def __str__(self):
        return self.nome


class Linguagem(models.Model):
    nome = models.CharField(max_length=30)

    def __str__(self):
        return self.nome


class Cadeira(models.Model):
    nome = models.CharField(max_length=20)
    ano = models.IntegerField()
    descricao = models.TextField()
    linguagens = models.ManyToManyField(Linguagem)
    docente_teorica = models.ForeignKey(Professor, on_delete=models.CASCADE)
    docentes_praticas = models.ManyToManyField(Professor, related_name='caderias')
    projetos = models.ManyToManyField(Projeto)

    def __str__(self):
        return f"{self.nome} {self.ano}"


class trabalhosFinaisCurso(models.Model):
    titulo = models.CharField(max_length=30)
    autores = models.TextField(default="Authors")
    orientadores = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to='pictures/', blank=True)
    ano = models.IntegerField()
    resumo = models.TextField(default="Text")
    relatorio = models.DateTimeField(auto_now_add=True)
    git = models.URLField()
    video = models.URLField()

    def __str__(self):
        return self.titulo[:20]

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post, Cadeira, Projeto


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
        # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição do titulo...'}),
            'descricao': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'descrição da tarefa...'}),
            'link': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'link do post...'}),
            'autor': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nome do autor...'}),

        }

        # texto a exibir junto à janela de inserção
        labels = {
            'titulo': 'Título',
            'descricao': 'Descrição',
            'link': 'Link',
            'autor': 'Autor',
        }

        # texto auxiliar a um determinado campo do formulário
        help_texts = {
            'link': 'Campo opcional',
        }


class CadeiraForm(ModelForm):
    class Meta:
        model = Cadeira
        fields = '__all__'


class ProjetoForm(ModelForm):
    class Meta:
        model = Projeto
        fields = '__all__'

portfolio/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from matplotlib import pyplot as plt

import datetime

from portfolio.forms import PostForm, CadeiraForm, ProjetoForm
from portfolio.models import Post, PontuacaoQuizz, Cadeira, Projeto, trabalhosFinaisCurso


def layout_view(request):
    return render(request, 'portfolio/layout.html')


def home_view(request):
    return render(request, 'portfolio/home.html')


def tempo_view(request):
    return render(request, 'portfolio/tempo.html')


def tfcdetails_view(request, tfc_id):
    tfc = trabalhosFinaisCurso.objects.get(pk=tfc_id)
    contexto = {'tfc': tfc}

    return render(request, 'portfolio/tfcdetails.html', contexto)


def trabalhosFinaisCurso_view(request):
    tfcs = trabalhosFinaisCurso.objects.all()
    contexto = {'tfcs': tfcs}
    return render(request, 'portfolio/tfc.html', contexto)


def apresentacao_view(request):
    return render(request, 'portfolio/apresentacao.html')


def formacao_view(request):
    return render(request, 'portfolio/formacao.html')


def contact_view(request):
    return render(request, 'portfolio/contact.html')


def projetos_view(request):
    form = ProjetoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:projetos'))
    context = {'projetos': Projeto.objects.all, 'form': form}
    return render(request, 'portfolio/projetos.html', context)


def competencias_view(request):
    return render(request, 'portfolio/competencias.html')


def blog_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {
        'posts': Post.objects.all(),
        'form': form
    }
    return render(request, 'portfolio/blog.html', context)


def index_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }

    return render(request, 'portfolio/home.html', context)


def licenciatura_view(request):
    form = CadeiraForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:licenciatura'))
    context = {'cadeiras': Cadeira.objects.all, 'form': form}
    return render(request, 'portfolio/licenciatura.html', context)


def heroPage_view(request):
    return render(request, 'portfolio/heroPage.html')


def quizz_view(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        r = PontuacaoQuizz(nome=n, pontuacao=p)
        r.save()
        desenha_grafico_resultados()

    return render(request, 'portfolio/quizz.html')


def pontuacao_quizz(request):
    pontuacao = 0
    if request.POST['pergunta1'] == "margem":
        pontuacao += 1

    if request.POST['pergunta2'] == "Css3":
        pontuacao += 1

    if request.POST['pergunta3'] == "margem":
        pontuacao += 1

    return pontuacao


def desenha_grafico_resultados():
    participantes = sorted(PontuacaoQuizz.objects.all(), key=lambda t: t.pontuacao)

    nomes = []
    pontuacoes = []

    for pt in participantes:
        nomes.append(pt.nome)
        pontuacoes.append(pt.pontuacao)

    nomes.reverse()
    pontuacoes.reverse()
    plt.barh(nomes, pontuacoes)
    plt.savefig("portfolio/static/portfolio/images/grafico.png", bbox_inches='tight')


def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(
            request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('portfolio:heroPage'))
        else:
            return render(request, 'portfolio/login.html', {
                'message': 'Credenciais invalidas.'
            })

    return render(request, 'portfolio/login.html')


def logout_view(request):
    logout(request)

    return render(request, 'portfolio/login.html', {
        'message': 'Foi desconetado.'
    })

portfolio/templates/portfolio/apresentacao.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Apresentação</h3>
    <p>Futura apresentacao </p>
    <p>Futura apresentacao </p>
{% endblock %}

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Blog</h3>
    <div class="lista">
    {% for post in posts %}
        <div>
            <h1>{{ post.titulo }}</h1>
            <p>{{ post.descricao }}<br> Por {{ post.autor }} a {{ post.data }}</p>
        </div>
    {% endfor %}
    </div>
     <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
{% endblock %}

portfolio/templates/portfolio/competencias.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Competências</h3>
    <p>Competências </p>
    <p>Competências </p>
{% endblock %}

portfolio/templates/portfolio/contact.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/contact.css' %}">


    <h3>Contact</h3>
    <section class="about">
        <div class="mainEstilo">
            {% load static %}
            <img src="{% static 'portfolio/images/xuxu.jpg' %}"/>
            <div class="about-text">

                <h2>Contact Me</h2>
                <p>Tel: +351 965 252 263<br>Email: afonsocautela@hotmail.com</p>
            </div>
        </div>

    </section>


{% endblock %}

portfolio/templates/portfolio/formacao.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Formação</h3>
    <p>Futura formação </p>

{% endblock %}

portfolio/templates/portfolio/heroPage.html
{% extends 'portfolio/layout.html' %}

<!DOCTYPE html>
<html lang="pt">

{% block main %}

<head>
    <meta charset="UTF-8">
    <meta name="author" content="Afonso Cautela">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200&display=swap" rel="stylesheet">
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/heroPage.css' %}">

    <title>HERO PAGE</title>
</head>

<body>
    <div>

        <header class="Cabecalho">
            <div>
                {% load static %}
                <video class="CabecalhoVideo"
                       src="{% static 'portfolio/images/deserto.mp4' %}" autoplay loop muted></video>
                <div class="TextoMenu">
                    <h1>Ou arriscas ou nunca saberás se vale a pena.</h1>
                </div>
            </div>
        </header>
    </div>



    <div class="capitais">
        <article>
            Ogólnie znana teza głosi, iż użytkownika może rozpraszać zrozumiała zawartość strony, kiedy ten chce zobaczyć sam jej wygląd. Jedną z mocnych stron używania Lorem Ipsum jest to, że ma wiele różnych „kombinacji” zdań, słów i akapitów, w przeciwieństwie do zwykłego: „tekst, tekst, tekst”, sprawiającego, że wygląda to „zbyt czytelnie” po polsku. Wielu webmasterów i designerów używa Lorem Ipsum jako domyślnego modelu tekstu i wpisanie w internetowej wyszukiwarce ‘lorem ipsum’ spowoduje znalezienie bardzo wielu stron, które wciąż są w budowie. Wiele wersji tekstu ewoluowało i zmieniało się przez lata, czasem przez przypadek, czasem specjalnie (humorystyczne wstawki itd).
        </article>
    </div>


    <div class="parallax2">
        <h1 style="color: rgb(243,243,243);">To be continued...</h1>
    </div>


</body>
</html>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<h3>Home</h3>
    {% load static %}
    <img src="{% static 'portfolio/images/trator-agricola2.jpg' %}" alt="">

    <p>Estamos em {{ local }}, são {{ hora }} horas e temos estes topicos {{ topicos }}.</p>
     <p>Lista de topicos que falaremos:</p>
        <ul>
                {% for topico in topicos %}
                      <li> {{ topico }} </li>
                {% endfor %}
        </ul>

    <p>
                {% if hora > 12 %}
                   Boa tarde,
                {% else %}
                   Bom dia,
                {% endif %}
                estamos em {{ local }}, e são {{ hora }} horas. </p>
{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>LAB8</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'portfolio/images/favicon.ico' %}">
    <script>function startTime() {
        const today = new Date();
        let h = today.getHours();
        let m = today.getMinutes();
        let s = today.getSeconds();
        m = checkTime(m);
        s = checkTime(s);
        document.getElementById('clk').innerHTML = h + ":" + m + ":" + s;
        setTimeout(startTime, 1000);
    }

    function checkTime(i) {
        if (i < 10) {
            i = "0" + i
        }
        return i;
    }</script>
    <script>document.addEventListener('DOMContentLoaded', function () {
        fetch('https://api.ipma.pt/open-data/forecast/warnings/warnings_www.json')
            .then(response => response.json())
            .then(data => {

                document.querySelector(".tempo").innerHTML = data[0].text + data[0].awarenessTypeName + " Dia " + data[0].startTime;
            });
    });</script>
    <script>const options = {
	method: 'GET',
	headers: {
		accept: 'application/json',
		'X-RapidAPI-Key': '08d0c27a28mshbda31efd3f2ab72p1e7a24jsnfb85499466c5',
		'X-RapidAPI-Host': 'matchilling-chuck-norris-jokes-v1.p.rapidapi.com'
	}
};

fetch('https://matchilling-chuck-norris-jokes-v1.p.rapidapi.com/jokes/random', options)
	.then(response => response.json())
	.then(response => document.querySelector(".chuck").innerHTML = "Um facto sobre o Chuck Norris:" + response.value)
	.catch(err => console.error(err));
    </script>

</head>

<body onload="startTime()">
    <header>
        <div>
            <h3>Afonso Cautela</h3>
        </div>
    <div id="clk"></div>
        <nav>
            <a href="{%  url 'portfolio:heroPage' %}">Home</a>
            <a href="{%  url 'portfolio:projetos' %}">Projetos</a>
            <a href="{%  url 'portfolio:licenciatura' %}">Licenciatura</a>
            <a href="{%  url 'portfolio:blog' %}">Blog</a>
            <a href="{%  url 'portfolio:quizz' %}">Quizz</a>
            <a href="{%  url 'portfolio:contact' %}">Contact</a>
            <a href="{%  url 'portfolio:tfc' %}">TFC's</a>
            <a href="{%  url 'portfolio:tempo' %}">Meteorologia</a>
            {% if request.user.is_authenticated %}
            <a href="{%  url 'portfolio:logout' %}">Logout</a>
            {% else %}
            <a href="{%  url 'portfolio:login' %}">Login</a>
            {% endif %}
        </nav>
    </header>
        <main>
            {% block main %}
            {% endblock main %}
        </main>
    <footer>ULHT 2022</footer>

</body>
</html>

portfolio/templates/portfolio/licenciatura.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/licenciatura.css' %}">


    <h3>Licenciatura</h3>
    <div class="container">
        {% for cadeira in cadeiras %}
            <div>
                <h2>{{ cadeira.nome }}</h2>
                <p>{{ cadeira.descricao }}</p>
            </div>
        {% endfor %}

        {% if request.user.is_authenticated %}
            <form action="" method="POST">
                <p>Crie Projetos</p>
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" value="Gravar" class="botao botao-sucesso">
            </form>
        {% endif %}
    </div>


{% endblock %}

portfolio/templates/portfolio/login.html
{% extends 'portfolio/layout.html' %}
{% block main %}

    <h3>Login</h3>

    {% if message %}
      <p> {{ message }} </p>
    {% endif %}

    <form method="POST">
        {% csrf_token %}
        <label>
            <input type="text" name="username" placeholder="Username">
        </label>
        <label>
            <input type="password" name="password" placeholder="Password">
        </label>

        <input type="submit" value="Login">
    </form>
{% endblock %}

portfolio/templates/portfolio/projetos.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/projetos.css' %}">


    <h3>Projetos</h3>
    <div class="container">
        {% for projeto in projetos %}
            <div>
                <h2>{{ projeto.nome }}</h2>
                <p>{{ projeto.descricao }}</p>
            </div>
        {% endfor %}
        {% if request.user.is_authenticated %}
            <form action="" method="POST">
                <p>Crie Projetos</p>
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" value="Gravar" class="botao botao-sucesso">
            </form>

        {% endif %}
    </div>

{% endblock %}

portfolio/templates/portfolio/tempo.html
{% extends 'portfolio/layout.html' %}
{% block main %}
    {% load static %}
    <p class="tempo"></p>
    <br>
    <br>
    <p class="chuck"></p>
{% endblock %}

portfolio/templates/portfolio/tfc.html
{% extends 'portfolio/layout.html' %}
{% block main %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/tfc.css' %}">

    <div class="portfolio">
        <h2 class="title">Latest Projects</h2>
        <a href="{% url 'portfolio:tfcdetails' tfcs.0.id %}" class="card">
            <div class="content">
                <span class="title">Web Design</span>
                <span class="category">Mobile / Design / Rebranding</span>
            </div>
            <div class="image">
                <img src="{% static 'portfolio/images/tfc1.PNG' %}"/>
            </div>
        </a>

        <a href="{% url 'portfolio:tfcdetails' tfcs.1.id %}" class="card">
            <div class="content">
                <span class="title">UX Design</span>
                <span class="category">UX / UI / Research </span>
            </div>
            <div class="image">
                <img src="{% static 'portfolio/images/tfc2.PNG' %}"/>
            </div>
        </a>

        <a href="{% url 'portfolio:tfcdetails' tfcs.2.id %}" class="card">
            <div class="content">
                <span class="title">Concepts</span>
                <span class="category">Design / Creative</span>
            </div>
            <div class="image">
                <img src="{% static 'portfolio/images/tfc3.PNG' %}"/>
            </div>
        </a>

        <a href="{% url 'portfolio:tfcdetails' tfcs.3.id %}" class="card">
            <div class="content">
                <span class="title">Creative & Cool</span>
                <span class="category">Design / Food</span>
            </div>
            <div class="image">
                <img src="{% static 'portfolio/images/tfc4.PNG' %}"/>
            </div>
        </a>

        <a href="{% url 'portfolio:tfcdetails' tfcs.4.id %}" class="card">
            <div class="content">
                <span class="title">AR-VR</span>
                <span class="category">VR / AR / Creative</span>
            </div>
            <div class="image">
                <img src="{% static 'portfolio/images/tfc5.PNG' %}"/>
            </div>
        </a>

        <a href="{% url 'portfolio:tfcdetails' tfcs.5.id %}" class="card">
            <div class="content">
                <span class="title">Logo</span>
                <span class="category">Design / Logo / Clothing</span>
            </div>
            <div class="image">
                <img src="{% static 'portfolio/images/tfc6.jpg' %}"/>
            </div>
        </a>


    </div>
{% endblock %}

portfolio/templates/portfolio/tfcdetails.html
{% extends 'portfolio/layout.html' %}
{% block main %}
    {% load static %}
    <h1>{{ tfc.titulo }}</h1>
<br>
    <p>{{ tfc.resumo }}</p>

    <p>Link para git: {{ tfc.git }}</p>


{% endblock %}